export const SUPPLIER_SELECT = 'SUPPLIER_SELECT';
export const SUPPLIERS_FETCH = 'SUPPLIERS_FETCH';
export const SUPPLIERS_ADD_TO_STATE = 'SUPPLIERS_ADD_TO_STATE';
export const SUPPLIER_ADD = 'SUPPLIER_ADD';
export const SUPPLIER_UPDATE = 'SUPPLIER_UPDATE';
export const SUPPLIER_PUT_UPDATE = 'SUPPLIER_PUT_UPDATE';
export const SUPPLIER_POST_ADD = 'SUPPLIER_POST_ADD';